### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by eliasmalik** [fac-freelancers/website#48]
Need to be careful of using features of JS that aren't universally supported. Both http://kangax.github.io/compat-table/es6 and caniuse.com should be your bible. If you really want these things, you must include polyfills.

You should also be doing cross-browser testing, and across older versions, not just the version of chrome that you're using.

Examples:
- [x] Use of `const`
- [x] Use of `Array.from`

**Comment by samhstn** [comment]
Fixed by commit #72
