### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by eliasmalik** [fac-freelancers/website#50]
Offset is wrong. When I scroll, I still get 10-20px of the previous section, and so the nav-bar highlighting is also on the wrong section.

**Comment by eliasmalik** [comment]
<img width="1228" alt="screen shot 2016-06-17 at 12 15 27" src="https://cloud.githubusercontent.com/assets/12719553/16148991/6ad864a2-3485-11e6-847d-dd990cc18432.png">

**Comment by samhstn** [comment]
Need to add `-webkit` for Chrome, Safari; `-moz` for Firefox, `-o` for Opera, `-ms` for Internet Explorer
and move the span which defines the section lower so that the nav bar highlights from the middle of the page not the top of the page

**Comment by samhstn** [comment]
Fixed by issue #71
